---
title: "STA 235H - Homework 2" # You can put the title of your document here
author: 
  - Name 1  # You can include names here
  - Name 2
  - Name 3
  - Name 4
date: "September 30th, 2021"
output: 
  pdf_document: 
    latex_engine: xelatex  # More modern PDF typesetting engine
    fig_width: 5
    fig_height: 4
    fig_caption: true # If you want to include captions for your figures (usually you do)
    toc: no #Do you want a Table of Contents?
header-includes:
   - \usepackage{float} #This is just a useful LaTeX package for positioning tables and figures
urlcolor: blue #This is so links are highlighted (and more visible)
---


<!-- Usually, you should load all your packages at the beginning. If you don't have a package installed, you'll need to do that first! -->
```{r setup, warning=FALSE, message=FALSE, echo=FALSE}
library(stargazer)
library(tidyverse)
library(modelsummary)
library(ggplot2)
library(estimatr)

knitr::opts_chunk$set(echo = TRUE)
```

# Task 1: Do training programs help? (25 points)

Suppose that Travis county has decided to implement a training program targeted at unemployed individuals with the objective that they gain computing skills, and with that, improve their resume and increase their chances of employment. The program has two different modalities: (1) long 6-month course, and (2) short 2-week crash course.

### Question 1.1

**In this context, how would you define the treatment variable? And what is the outcome of interest?** *(Hint: Think about this as an action someone takes, like "taking an aspirin")*

*[Answer here]*

### Question 1.2

**How many potential outcomes are there in this example? Define them in the context of this example** *(Hint: No need for math expressions here)*.

*[Answer here]*

### Question 1.3

**For assessing the effect of the program, the county has yearly employment records for its residents. To evaluate the policy, they compare outcomes for participants vs. non- participants. Is this a causal effect of the program? If not, give one example of selection bias and one example of heterogeneous return to treatment bias, as defined in class.** *(Note: For the purpose of this question, you can assume that you group everyone that took the training program together, independent of their modality)*

*[Answer here]*
