% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
  \usepackage{amssymb}
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={RMarkdown Template},
  pdfauthor={Magdalena Bennett},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{RMarkdown Template}
\author{Magdalena Bennett}
\date{August 16th, 2021}

\begin{document}
\maketitle

\hypertarget{rmarkdown-is-awesome}{%
\section{Rmarkdown is awesome}\label{rmarkdown-is-awesome}}

It make take a bit more time, but the flexibility that Rmarkdown gives
you (and the aesthetics 😍) is unbeatable\footnote{If you want to learn
  how to use emojis on your Rmarkdown files, go to
  \url{https://github.com/hadley/emo}}. This file is meant to act as a
template and it includes some basic comments (both here and in the
accompanying .css file), so it can be easily customized.

Don't despair! You might start like this:

\includegraphics{https://github.com/maibennett/sta235/blob/main/exampleSite/content/Classes/Week0/1_Rmarkdown/images/knits2.png?raw=true}

\ldots{} But you'll end up like this:

\includegraphics{https://github.com/maibennett/sta235/blob/main/exampleSite/content/Classes/Week0/1_Rmarkdown/images/cool_beans.jpeg?raw=true}

\hypertarget{pagedown-ftw}{%
\section{Pagedown FTW}\label{pagedown-ftw}}

We are going to be using the package \texttt{pagedown}\footnote{Go to
  \url{https://rstudio.github.io/pagedown/} to read all about it!}. This
is because it's very versatile for transforming documents that need to
be printed (or exported into pdf) and also working on HTML. If you ever
want to transition into making presentations in Rmarkdown (with
\texttt{Xaringan}, of course), this will be an easy step. I also find
css more manageable than the templates created for \(\LaTeX\).

\hypertarget{css-files-are-your-best-friend}{%
\section{.css files are your best
friend}\label{css-files-are-your-best-friend}}

I've included a \texttt{style.css} file that should be included in the
same folder that your Rmarkdown file (for simplicity, I haven't included
a path). There, you can make all aesthetic changes for your document (in
css). The advantage is that you can just copy that file (or create new
ones) for future Rmarkdown templates, and it's great!

\newpage

\hypertarget{lets-see-some-examples}{%
\section{Let's see some examples}\label{lets-see-some-examples}}

\hypertarget{how-latex-works}{%
\subsection{\texorpdfstring{How \(\LaTeX\)
works}{How \textbackslash LaTeX works}}\label{how-latex-works}}

Well, it works pretty much the same as \(\LaTeX\). Include inline
equations like: \(y_i = \beta_0 + \beta_1\cdot x_i + \varepsilon_i\), or
multiple line equations:

\[\begin{align}
y_i =& \beta_0 + \beta_1 x_{i1} + \beta_2 x_{i2} + \beta_3 x_{i3} +\\
    &\beta_4 x_{i4} + ... + \varepsilon_{i}
\end{align}\]

\hypertarget{lets-code}{%
\subsection{Let's code}\label{lets-code}}

We can write some simple code, if we want to show it (\emph{Tip: Include
\texttt{message=FALSE} and \texttt{warning=FALSE} so you don't get that
extra stuff when you run the code}):

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(cars)}

\FunctionTok{lm}\NormalTok{(speed }\SpecialCharTok{\textasciitilde{}}\NormalTok{ dist, }\AttributeTok{data =}\NormalTok{ cars)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = speed ~ dist, data = cars)
## 
## Coefficients:
## (Intercept)         dist  
##      8.2839       0.1656
\end{verbatim}

\newpage

Meh, but that output looks ugly. Can we make it prettier? Let's try
\texttt{stargazer} (you will need to include the
\texttt{results=\textquotesingle{}asis\textquotesingle{}} argument).

Regression of Speed on Distance

Dependent variable:

speed

My Model

dist

0.166***

(0.017)

Constant

8.284***

(0.874)

Observations

50

R2

0.651

Adjusted R2

0.644

Residual Std. Error

3.156 (df = 48)

F Statistic

89.567*** (df = 1; 48)

Note:

\emph{p\textless0.1; \textbf{p\textless0.05; }}p\textless0.01

Check out the different arguments that you might have, and play around.

\hypertarget{lets-plot}{%
\section{Let's plot}\label{lets-plot}}

Finally, let's briefly look into plots. For this, I'm using the package
\texttt{hrbrthemes}. Check it out
\href{https://github.com/hrbrmstr/hrbrthemes}{here!}.

I'm also saving these as .svg for resolution purposes.

\begin{center}\includegraphics{RMarkdown_Examples_PDF_files/figure-latex/example-1} \end{center}

\ldots{} and for Andrew Baker's sake, we can also rotate the y-axis
label (remember to rename your code chunk!)

\begin{center}\includegraphics{RMarkdown_Examples_PDF_files/figure-latex/example_rot-1} \end{center}

\hypertarget{come-to-the-dark-html-side}{%
\section{Come to the dark {[}HTML{]}
side\ldots{}}\label{come-to-the-dark-html-side}}

If you want to see how this would look as HTML, just change your YAML
(i.e.~the header of this document, between --- and ---) for the
following:

I've included a separate R markdown file with this, that you can knit
and see how the HTML file looks. I've also uploaded it \href{}{here}
just for fun 🥳.

If you want to share your HTML files, a super quick way is
\href{https://twitter.com/grant_mcdermott}{Grant McDermottt's}
suggestion using Github:

\includegraphics{https://twitter.com/grant_mcdermott}

\hypertarget{some-additional-resources}{%
\section{Some additional resources}\label{some-additional-resources}}

There are \textbf{tons} of resources out there, but some of my favorite
almost always come for \href{https://twitter.com/apreshill}{Alison
Preshill}. Check out her website!

Some additional material that could be useful:

\begin{itemize}
\item
  Xie, Y., J. J. Allaire, \& G. Grolemund (2021).
  \href{https://bookdown.org/yihui/rmarkdown/}{``Rmarkdown: The
  definitive guide''}
\item
  Xie, Y., C. Dervieux, \& E. Riederer (2020).
  \href{https://bookdown.org/yihui/rmarkdown-cookbook/}{``R Markdown
  Cookbook''}
\end{itemize}

\end{document}
