---
title: "Week 8 - In-Class Exercise"
author: "STA 235H - Fall 2023"
date: ""
output: 
  html_document:
    css: style.css
    df_print: "kable"
---
<style type="text/css">
div.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}

@media only screen and (max-width: 600px) {
   body {
      margin: 0;
      padding: 0;
   }
   .sample {
      width: 100%;
   }
}
</style>

# Setup

Most (if not all) countries have a minimum legal drinking age (MLDA), and people often ask if this makes sense or not. Should the MLDA be higher or lower or even exist at all? One way to think about this is to look at the external benefits of this, for example in health outcomes or crime.

In this exercise, we will be working with real arrest data from the California Department of Justice's Monthly Arrest and Citation register (MACR) between 1979 and 2006 for individuals between 18 and 24 years old (data is from paper by Carpenter & Dobkin (2015)) to tackle this question.


```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(rdrobust)

mlda = read.csv("https://raw.githubusercontent.com/maibennett/sta235/main/exampleSite/content/Classes/Week8/1_RDD/data/mlda_18_24.csv")
```

Here's the list of some variables in your dataset:

- `age_days`: Age of the people arrested, in days (we will assume 7670 days = 21 years)
- `all`: Total number of arrests
- `felony`: Total number of felonies arrests
- `murder`: Total number of murder arrests
- `assault`: Total number of assault arrests
- `alcohol`: Total number of arrests related to alcohol
- `dui`: : Total number of driving under the influece arrests
- `female`: Proportion of female arrests (sim)

## Tasks

1) Let's start creating the variables we will need! Create a running variable `r` centered around the 21st birthday (*Hint: You will need to use age and subtract the cutoff*), and a treatment variable `treat` that takes the value of (1) if the person can legally drink and 0 in another case.


2) Let's do some robustness checks first to make sure we can fit a RDD. Using `rdplot()`, show a plot for a RDD with `treat` as your outcome and `r` as your running variable. Do you see a discontinuity?


3) Let's do another robustness check, by checking the smoothness of covariates across the threshold. Using `rdplot()` and `rdrobust()`, fit a RDD with `female` as your outcome and `r` as your running variable. Should you see a discontinuity?


4) Finally, let's calculate an effect! Use a linear model (`lm()`) to estimate the RDD, using `alcohol` as your outcome, and compare it to the results of `rdrobust()`. Include a plot using `rdplot()`. Which one do you think is a better estimate? Interpret your  effect.


*At home: Try the same analysis but for a different outcome (e.g. DUI or assault). What do you find?*
