---
title: "STA 235 - FINAL EXAM"
subtitle: "Spring 2021"
author: "McCombs School of Business, UT Austin"
output:
  xaringan::moon_reader:
    css: ["xaringan-themer.css", "custom.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
      beforeInit: ["macros.js","cols_macro.js"]
    includes:
      in_header: header.html
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(fig.showtext = TRUE)
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)

theme_xaringan(
  text_color = "#333f48",
  background_color = "#FFFFFF",
  accent_color = "#900DA4",
  text_font = "Fira Mono",
  text_font_use_google = TRUE,
  title_font = "Yanone Kaffeesatz",
  title_font_use_google = TRUE
)

style_mono_accent(
  #base_color = "#bf5700",
  extra_fonts = list(google_font("Fira Sans","200","300","400","500","600"),
                     google_font("Fira Sans Condensed","200","300","400","500","600")),
  base_color = "#333f48",
  header_font_google = google_font("Yanone Kaffeesatz","200","300","400","500","600","700"),
  text_font_google   = google_font("Roboto", "300", "300i","400","500"),
  code_font_google   = google_font("Fira Mono"),
  text_bold_color = "#333f48",
  text_font_size = "125%",
  colors = c(
    lightgrey = "#C0C0C0",
    red = "#f34213",
    purple = "#900DA4",
    darkpurple = "#61077a",
    darkorange = "#db5f12",
    orange = "#ff8811",
    green = "#136f63",
    white = "#FFFFFF"),
  extra_css = list(
    ".remark-slide table" = list("display" = "table",
                   "width" = "80%",
                   "text-align" = "left"),
    ".remark-slide-number" = list("display" = "none"),
    ".strong" = list("font-weight" = "400"),
    ".big" = list("font-size" = "350%",
                     "font-family" = "Yanone Kaffeesatz",
                     "font-weight"="400"),
    ".small" = list("font-size" = "80%"),
    ".tiny" = list("font-size" = "50%"),
    ".large" = list("font-size" = "150%"),
    ".source" = list("color" = "#8c8c8c",
                     "font-size" = "80%"),
    ".remark-slide table td#highlight" = list("background-color" = "#eee1f0",
                                  "color" = "#900DA4",
                                  "font-weight" = "500"),
   # ".remark-slide table thead th" = list(),
    ".title-slide h1" = list("font-weight" = "500"),
    ".title-slide h2" = list("font-weight" = "400",
                             "font-size" =  "170%"),
    ".title-slide h3" = list("font-family" = "Roboto",
                             "font-size" = "100%",
                             "font-weight" = "200"),
    ".center2" = list("margin" = "0",
                      "position" = "absolute",
                      "top" = "50%",
                      "left" = "50%",
                      "-ms-transform" = "translate(-50%, -50%)",
                      "transform" = "translate(-50%, -50%)"),
   ".bottom2" = list("margin" = "0",
                      "position" = "absolute",
                      "top" = "90%",
                      "left" = "10%",
                      "-ms-transform" = "translate(-10%, -90%)",
                      "transform" = "translate(-10%, -90%)"),
    ".section-title h1" = list("color" = "#FFFFFF",
                               "font-size" = "2.3em",
                               "line-height" = "1.3"),
    ".medium" = list("font-size" = "1.4em"),
    ".sp-after-half" = list("margin-bottom" = "0.7em !important"),
    ".box-1,.box-1a,.box-1s,.box-1b,.box-1l,.box-1LA,.section-title-1" = list("background-color" = "#0D0887"),
    ".box-2,.box-2a,.box-2s,.box-2b,.box-2l,.box-2LA,.section-title-2" = list("background-color" = "#5601A4"),
    ".box-3,.box-3a,.box-3s,.box-3b,.box-3l,.box-3LA,.section-title-3" = list("background-color" = "#900DA4"),
    ".box-4,.box-4a,.box-4s,.box-4b,.box-4l,.box-4LA,.section-title-4" = list("background-color" = "#BF3984"),
    ".box-5,.box-5a,.box-5s,.box-5b,.box-5l,.box-5LA,.section-title-5" = list("background-color" = "#E16462"),
    ".box-6,.box-6a,.box-6s,.box-6b,.box-6l,.box-6LA,.section-title-6" = list("background-color" = "#F89441"),
    ".box-7,.box-7a,.box-7s,.box-7b,.box-7l,.box-7LA,.section-title-7" = list("background-color" = "#FCCE25"),
   
   ".box-1t,.box-1tL,.section-title-1t" = list("background-color" = "rgba(13, 8, 135,0.3)",
                                      "color"="rgba(13, 8, 135,1)",
                                      "font-family" = "Yanone Kaffeesatz",
                                                                    "border-radius" = "15px"),
    ".box-2t,.box-2tL,.section-title-2t" = list("background-color" = "rgba(86, 1, 164,0.3)",
                                       "color" = "rgba(86, 1, 164,1)",
                                       "font-family" = "Yanone Kaffeesatz",
                                                                    "border-radius" = "15px"),
    ".box-3t,.box-3tL,.section-title-3t" = list("background-color" = "rgba(144, 13, 164,0.3)",
                                       "color" = "rgba(144, 13, 164,1)",
                                       "font-family" = "Yanone Kaffeesatz",
                                                                    "border-radius" = "15px"),
    ".box-4t,.box-4tL,.section-title-4t" = list("background-color" = "rgba(191, 57, 132,0.3)",
                                       "color" = "rgba(191, 57, 132,1)",
                                       "font-family" = "Yanone Kaffeesatz",
                                                                    "border-radius" = "15px"),
    ".box-5t,.box-5tL,.section-title-5t" = list("background-color" = "rgba(225, 100, 98,0.3)",
                                       "color" = "rgba(225, 100, 98,1)",
                                       "font-family" = "Yanone Kaffeesatz",
                                                                    "border-radius" = "15px"),
    ".box-6t,.box-6tL,.section-title-6t" = list("background-color" = "rgba(248, 148, 65,0.3)",
                                       "color" = "rgba(248, 148, 65,1)",
                                       "font-family" = "Yanone Kaffeesatz",
                                                                    "border-radius" = "15px"),
    ".box-7t,.box-7tL,.section-title-7t" = list("background-color" = "rgba(252, 206, 37,0.3)",
                                       "color" = "rgba(252, 206, 37,1)",
                                       "font-family" = "Yanone Kaffeesatz",
                                                                    "border-radius" = "15px"),
   
   ".box-7t, .box-6t, .box-5t, .box-4t, .box-3t, .box-2t, .box-1t" = list("margin" = "0em auto",
                                                                    "overflow" = "hidden",
                                                                    "padding" = "0.4em 0.4em",
                                                                    "font-weight" = "600",
                                                                    "font-size" = "31px",
                                                                    "display" = "table",
                                                                    "text-align" = "center",
                                                                    "border-radius" = "15px"),
   
   ".box-7tL, .box-6tL, .box-5tL, .box-4tL, .box-3tL, .box-2tL, .box-1tL" = list("margin" = "0em auto",
                                                                    "overflow" = "hidden",
                                                                    "padding" = "0.4em 0.4em",
                                                                    "font-weight" = "600",
                                                                    "font-size" = "50px",
                                                                    "display" = "table",
                                                                    "text-align" = "center",
                                                                    "border-radius" = "15px"),
   
    ".box-7, .box-6, .box-5, .box-4, .box-3, .box-2, .box-1" = list("color" = "#FFFFFF",
                                                                    "margin" = "0em auto",
                                                                    "overflow" = "hidden",
                                                                    "padding" = "0.4em 0.4em",
                                                                    "font-weight" = "600",
                                                                    "font-size" = "31px",
                                                                    "display" = "table",
                                                                    "text-align" = "center",
                                                                    "font-family" = "Fira Sans",
                                                                    "border-radius" = "15px"),
    ".box-7a, .box-6a, .box-5a, .box-4a, .box-3a, .box-2a, .box-1a" = list("color" = "#FFFFFF",
                                                                          "left" = "0px",
                                                                          "overflow" = "hidden",
                                                                      "padding" = "0.4em 0.4em",
                                                                      "font-weight" = "600",
                                                                      "font-size" = "25px",
                                                                      "display" = "table",
                                                                      "text-align" = "center",
                                                                      "font-family" = "Fira Sans",
                                                                    "border-radius" = "15px"),
   ".box-7s, .box-6s, .box-5s, .box-4s, .box-3s, .box-2s, .box-1s" = list("color" = "#FFFFFF",
                                                                          "left" = "0px",
                                                                          "overflow" = "hidden",
                                                                      "padding" = "0.2em 0.2em",
                                                                      "font-weight" = "400",
                                                                      "font-size" = "100%",
                                                                      "display" = "inline",
                                                                      "text-align" = "center",
                                                                      "font-family" = "Fira Sans",
                                                                    "border-radius" = "15px"),
       ".box-7b, .box-6b, .box-5b, .box-4b, .box-3b, .box-2b, .box-1b" = list("color" = "#FFFFFF",
                                                                          "left" = "0px",
                                                                          "overflow" = "hidden",
                                                                      "padding" = "0.4em 0.4em",
                                                                      "font-weight" = "600",
                                                                      "font-size" = "25px",
                                                                      "display" = "table",
                                                                      "text-align" = "left",
                                                                      "font-family" = "Fira Sans",
                                                                    "border-radius" = "15px"),
   ".box-7l, .box-6l, .box-5l, .box-4l, .box-3l, .box-2l, .box-1l" = list("color" = "#FFFFFF",
                                                                    "margin" = "0em auto",
                                                                    "overflow" = "hidden",
                                                                    "padding" = "0.4em 0.4em",
                                                                    "font-weight" = "600",
                                                                    "font-size" = "45px",
                                                                    "display" = "table",
                                                                    "text-align" = "center",
                                                                      "font-family" = "Yanone Kaffeesatz",
                                                                    "border-radius" = "15px"),
   ".box-7LA, .box-6LA, .box-5LA, .box-4LA, .box-3LA, .box-2LA, .box-1LA" = list("color" = "#FFFFFF",
                                                                    "margin" = "0em auto",
                                                                    "overflow" = "hidden",
                                                                    "padding" = "0.4em 0.4em",
                                                                    "font-weight" = "600",
                                                                    "font-size" = "55px",
                                                                    "display" = "table",
                                                                    "text-align" = "center",
                                                                      "font-family" = "Yanone Kaffeesatz",
                                                                    "border-radius" = "15px"),
   ".image-80 img" = list("scale" = "80%"),
   ".pull-left-little_l" = list("float" = "left",
                                "width" = "67%"),
   ".pull-right-little_l" = list("float" = "right",
                                "width" = "27%"),
   ".pull-left-little_r" = list("float" = "left",
                                "width" = "27%"),
   ".pull-right-little_r" = list("float" = "right",
                                "width" = "67%")


  )
)

#,"li" = list("font-size" = "150%")
#    "li" = list("font-size" = "110%"),
#    "ul" = list("font-size" = "110%"),
#color palette
#5601A4
#900DA4
#F89441
#FCCE25

knitr::opts_chunk$set(message = FALSE)

```
```{css, echo = FALSE}

.small .remark-code { /*Change made here*/
  font-size: 80% !important;
}

.tiny .remark-code { /*Change made here*/
  font-size: 90% !important;
}
```

```{r setup2, echo=FALSE, message=FALSE}
library(knitr)
library(showtext)
library(xaringanExtra)

#xaringanExtra::use_scribble()

htmltools::tagList(
  xaringanExtra::use_clipboard(
    button_text = "<i class=\"fa fa-clipboard\"></i>",
    success_text = "<i class=\"fa fa-check\" style=\"color: #90BE6D\"></i>",
    error_text = "<i class=\"fa fa-times-circle\" style=\"color: #F94144\"></i>"
  ),
  rmarkdown::html_dependency_font_awesome()
)
```

```{r fonts, message=FALSE, echo=FALSE}
font.add.google("Fira Sans Condensed", "Fira Sans Condensed")
font.add.google("Fira Sans", "Fira Sans")
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(gganimate)
library(ggthemes)
library(gifski)
library(plotly)
library(leaflet)
library(ggplot2)
library(firasans)
library(hrbrthemes)
library(extrafont)
library("RColorBrewer")
library(viridis)
library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")
library("firasans")
library(hrbrthemes)
library(extrafont)
library(countdown)
library(htmltools)

options(scipen = 0)
```

# Final Exam

.box-2[sta235.netlify.app/exams/final/YOUR_EID]
<br>
.box-3[This exam is open-book. But you can't communicate with anyone.]
<br>
.box-4[Keep your camera on]
<br>
.box-5[Ask questions on the chat]
<br>
.box-6[You have 2 hours]
<br>
.box-7[Good luck!]


---
<br>

.box-3tL[sta235.netlify.app/exams/final/YOUR_EID]

<br>
<br>
.center[
```{r, echo=FALSE}

countdown <- function(
  minutes = 1L,
  seconds = 0L,
  ...,
  id = NULL,
  class = NULL,
  style = NULL,
  play_sound = FALSE,
  font_size = "3em",
  margin = "0.6em",
  padding = "10px 15px",
  bottom = if (is.null(top)) "0",
  right = if (is.null(left)) "0",
  top = NULL,
  left = NULL,
  warn_when = 0L,
  update_every = 1L,
  blink_colon = update_every > 1L,
  box_shadow = "0px 4px 10px 0px rgba(50, 50, 50, 0.4)",
  border_width = "3px",
  border_radius = "15px",
  line_height = "1",
  color_border = "#ddd",
  color_background = "inherit",
  color_text = "inherit",
  color_running_background = "#43AC6A",
  color_running_border = darken(color_running_background, 0.1),
  color_running_text = NULL,
  color_finished_background = "#F04124",
  color_finished_border = darken(color_finished_background, 0.1),
  color_finished_text = NULL,
  color_warning_background = "#E6C229",
  color_warning_border = darken(color_warning_background, 0.1),
  color_warning_text = NULL
) {
  time <-  minutes * 60 + seconds
  minutes <- as.integer(floor((time)/60))
  seconds <- as.integer(time - minutes * 60)
  stopifnot(minutes < 180)
  warn_when <- suppressWarnings(as.integer(warn_when))
  if (is.na(warn_when)) {
    stop("`warn_when` must be an integer number of seconds")
  }
  
  if (is.null(id)) {
    uid <- make_unique_id()
    id <- paste0("timer_", uid)
  }
  id <- validate_html_id(id)
  
  class <- paste(unique(c("countdown", class)), collapse = " ")
  
  if (blink_colon) class <- paste(class, "blink-colon")
  
  update_every <- as.integer(update_every)
  if (update_every > 1L) {
    class <- paste0(class, " noupdate-", update_every)
  }
  
  `%:?%` <- function(x, y) if (!is.null(x)) paste0(y, ":", x, ";")
  
  x <- div(
    class = class,
    id = id,
    style = paste0(
      top %:?% "top",
      right %:?% "right",
      bottom %:?% "bottom",
      left %:?% "left",
      if (!missing(margin)) margin %:?% "margin",
      if (!missing(padding)) padding %:?% "padding",
      if (!missing(font_size)) font_size %:?% "font-size",
      if (!missing(line_height)) line_height %:?% "line-height",
      paste(style, collapse = "; ")
    ),
    code(
      class = "countdown-time",
      HTML(
        paste0(
          span(class = "countdown-digits minutes", sprintf("%02d", minutes)),
          span(class = "countdown-digits colon", ":"),
          span(class = "countdown-digits seconds", sprintf("%02d", seconds))
        )
      )
    )
  )
  
  if (isTRUE(play_sound)) {
    x$attribs$`data-audio` <- "true"
  } else if (is.character(play_sound) && nzchar(play_sound)) {
    x$attribs$`data-audio` <- play_sound
  }
  x$attribs$`data-warnwhen` <- if (warn_when > 0) warn_when else 0L
  
  tmpdir <- tempfile("countdown")
  dir.create(tmpdir)
  file.copy(system.file("countdown.js", package = "countdown"),
            file.path(tmpdir, "countdown.js"))
  file.copy(system.file("smb_stage_clear.mp3", package = "countdown"),
            file.path(tmpdir, "smb_stage_clear.mp3"))
  
  # Set text based on background color
  color_running_text <- color_running_text %||%
    choose_dark_or_light(color_running_background)
  color_finished_text <- color_finished_text %||%
    choose_dark_or_light(color_finished_background)
  color_warning_text <- color_warning_text %||%
    choose_dark_or_light(color_warning_background)
  
  css_template <- readLines(system.file("countdown.css", package = "countdown"))
  css <- whisker::whisker.render(css_template)
  css_file <- file.path(tmpdir, "countdown.css")
  writeLines(css, css_file)
  
  htmltools::htmlDependencies(x) <- htmlDependency(
    "countdown",
    version = utils::packageVersion("countdown"),
    src = gsub("//", "/", dirname(css_file)),
    script = "countdown.js",
    stylesheet = "countdown.css",
    all_files = TRUE
  )
  
  htmltools::browsable(x)
}

#' @describeIn countdown A full-screen timer that takes up the entire view port
#'   and uses the largest reasonable font size.
#'
#' @export
countdown_fullscreen <- function(
  minutes = 1,
  seconds = 0,
  ...,
  font_size = "30vw",
  border_width = "0",
  border_radius = "0",
  margin = "0",
  padding = "0",
  top = 0,
  right = 0,
  bottom = 0,
  left = 0
) {
  countdown(
    minutes, seconds,
    font_size = font_size,
    border_width = border_width,
    border_radius = border_radius,
    margin = margin,
    padding = padding,
    top = top, right = right, bottom = bottom, left = left,
    ...
  )
}


make_unique_id <- function(safe = TRUE) {
  uniqid <- function() as.hexmode(as.integer(Sys.time() + stats::runif(1) * 1000))
  
  if (!safe) return(uniqid())
  callr::r_safe(
    function() countdown:::make_unique_id(safe = FALSE)
  )
}

validate_html_id <- function(id) {
  stop_because <- function(...) {
    stop(paste0('"', id, '" is not a valid HTML ID: ', ...))
  }
  if (!grepl("^[a-zA-Z]", id)) {
    stop_because("Must start with a letter")
  }
  if (grepl("[^0-9a-zA-Z_:.-]", id)) {
    invalid <- gsub("[0-9a-zA-Z_:.-]", "", id)
    invalid <- strsplit(invalid, character(0))[[1]]
    invalid <- unique(invalid)
    invalid[invalid == " "] <- "' '"
    invalid <- paste(invalid, collapse = ", ")
    stop_because('Cannot contain the character',
                 if (nchar(invalid) > 1) "s: ", invalid)
  }
  id
}


countdown(minutes = 130, seconds = 0, update_every = 60, play_sound = TRUE, box_shadow = TRUE, right = "30%", bottom = "33%",
          color_border = "#5601A4",
          color_text = "#5601A4",
          color_running_background  = "#900DA4",
          color_running_text        = "white",
          color_finished_background = "#E16462",
          color_finished_text       = "white",
          border_width = "5px",
          font_size = "4em")
```
]